image: python

stages:
- build
- style
- test
- integrationtest
- systemtest
- coverage
- release

before_script:
- pip install pip --upgrade
- pip install -r dev-requirements.txt

# -------------- Build --------------
build:
  stage: build
  script: tox -e build
  artifacts:
    paths:
    - dist/
    expire_in: 1 week

# -------------- Style tests --------------
flake8:
  image: python:3.7
  stage: style
  script: tox -e flake8

readme:
  image: python:3.7
  stage: style
  script: tox -e readme

docs:
  image: python:3.7
  stage: style
  script: tox -e docs

# -------------- Unit tests --------------
python36:
  image: python:3.6
  stage: test
  script: tox -e py36-unit
  artifacts:
    - .tox/.coverage*

python37:
  image: python:3.7
  stage: test
  script: tox -e py37-unit

python38:
  image: python:3.8
  stage: test
  script: tox -e py38-unit

# -------------- Integration tests --------------
python36-gpaw:
  image: python:3.6
  stage: integrationtest
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev liblapack-dev libxc-dev
    - tox -e py36-gpaw

python37-gpaw:
  image: python:3.7
  stage: integrationtest
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev liblapack-dev libxc-dev
    - tox -e py37-gpaw

python38-gpaw:
  image: python:3.8
  stage: integrationtest
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev liblapack-dev libxc-dev
    - tox -e py38-gpaw

# -------------- System tests --------------
python36-gpaw-2dsystem:
  image: python:3.6
  stage: systemtest
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev liblapack-dev libxc-dev
    - tox -e 2dsystem
  timeout: 1h
  when: manual
# allow_failure: false

# -------------- Coverage --------------

coverage:
  image: python:3.7
  stage: coverage
  script:
    - tox -e coverage-report

# -------------- Release --------------
# (Only on git tagged commit)
release:
  stage: release
  script: tox -e release
  artifacts:
    paths:
    - dist
  only:
    - tags