tests:
  image:  python:3.6
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev liblapack-dev libxc-dev
    - pip install flake8 spglib
    - pip install -e .
    - pip install git+https://gitlab.com/ase/ase.git
    - pip install gpaw
    - gpaw install-data paw-datasets --register
    - asr test -k test_fast.py,asr.utils.cli,asr.setup.params,asr.relax
    - flake8 asr
