tests:
  image:  python:3.6
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev liblapack-dev libxc-dev
    - pip install flake8 spglib
    - pip install -e .
    - pip install git+https://gitlab.com/ase/ase.git
    - pip install gpaw
    - python3 -m pytest asr/tests/test_cli.py asr/tests/test_style.py --tb=short
    - python3 -m pytest asr/tests/emt.py --tb=short
    - flake8 asr
