tests:
  image:  python:3.6
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev liblapack-dev libxc-dev
    - pip install flake8
    - pip install -e .
    - pip install gpaw
    - gpaw install-data paw-datasets --register
    - asr test asr.utils.cli asr.setup.params asr.relax_0 --raiseexc
    - flake8 asr

docs_test:
  image: python:3
  script:
    - pip install .[docs]
    - which sphinx-build
    - cd $CI_PROJECT_DIR/docs
    - sphinx-build -W . build