tests:
  image:  python:3.6
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev liblapack-dev libxc-dev
    - pip install flake8 coverage
    - pip install -e .
    - flake8 asr
    - pip install gpaw
    - gpaw install-data paw-datasets --register
    - tdir=$(mktemp -d /tmp/asr-test-XXXXXXXXX)
    - coverage run -m asr test asr.utils.cli asr.setup.params asr.relax_0 --tmpdir $tdir
    - coverage combine $tdir/*/.coverage.* .coverage.*
    - coverage report --include '*/asr/asr/*'
    - coverage run -m asr test  --raiseexc
    - coverage report -i --include="*asr/asr/*"


docs_test:
  image: python:3.6
  script:
    - pip install .[docs]
    - which sphinx-build
    - cd $CI_PROJECT_DIR/docs
    - sphinx-build -W . build