stages:
  - test
  - deploy


lint:
  image: registry.gitlab.com/ase/ase:ase-paperwork
  script:
   - flake8 asr/


docs:
  image: registry.gitlab.com/asr-dev/asr:main
  script:
    - sphinx-build --keep-going -E -W -c docs -b html docs docs/build


main:
  image:  registry.gitlab.com/asr-dev/asr:main
  timeout: 20m
  script:
    - pytest asr/test --color=yes --numprocesses=auto --cov=asr --cov-report=html --durations 20
    - coverage report

  coverage: '/TOTAL.+ ([0-9]+\.[0-9]+%)/'
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 week


parallel:
  image: registry.gitlab.com/asr-dev/asr:main
  timeout: 20m
  script:
    - mpiexec --oversubscribe -np 2 gpaw python -m pytest -- asr/test -m parallel --color=yes --durations 20


pages:
  stage: deploy
  dependencies:
    - main
  script:
    - mv htmlcov public
  artifacts:
    paths:
      - public
    expire_in: 3 weeks
  only:
    - master


# XXX Should re-enable asr-test-data:
#  script:
#    - git clone https://gitlab.com/asr-dev/asr-test-data.git
#    - export ASR_TEST_DATA="$PWD"/asr-test-data
