tests:
  image:  python:3.6
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev liblapack-dev libxc-dev
    - pip install flake8 spglib
    - pip install -e .
    - pip install gpaw
    - gpaw install-data paw-datasets --register
    - asr test -k asr.utils.cli,asr.setup.params,asr.relax_0
    - flake8 asr
