image: python


stages:
  - test
  - deploy


flake8:
  image: registry.gitlab.com/ase/ase:ase-paperwork
  script:
   - flake8 asr/


docs:
  image: registry.gitlab.com/asr-dev/asr:main
  script:
    - sphinx-build --keep-going -E -W -c docs -b html docs docs/build


# GPAW stuff fails as of 2023-02-03 when using shared runners on
# our test docker.  Disable parallel stuff for now.
# Also when this is fixed, re-enable the xfailed test i test_relax.py.
.parallel:
  image: registry.gitlab.com/asr-dev/asr:main
  stage: test
  script:
    - cd asr/test
    - mpiexec --oversubscribe -np 2 gpaw python -m pytest -- -m parallel


main:
  image:  registry.gitlab.com/asr-dev/asr:main
  stage: test
  script:
    - pwd
    - cd asr/test
    - pytest --color=yes --numprocesses=auto --cov=asr --cov-report=html
    - coverage report

  coverage: '/TOTAL.+ ([0-9]+\.[0-9]+%)/'
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 week


.pages:
  stage: deploy
  dependencies:
    - main
  script:
    - mv htmlcov public
  artifacts:
    paths:
      - public
    expire_in: 3 weeks
  only:
    - master
