image: python


stages:
  - test
  - deploy


flake8:
  image: registry.gitlab.com/ase/ase:ase-paperwork
  script:
   - flake8 asr/


docs:
  image: registry.gitlab.com/asr-dev/asr:main
  script:
    - sphinx-build --keep-going -E -W -c docs -b html docs docs/build


parallel:
  image: registry.gitlab.com/asr-dev/asr:main
  stage: test
  script:
    - cd asr/test
    - mpiexec --oversubscribe -np 2 gpaw python -m pytest -- -m parallel


main:
  image:  registry.gitlab.com/asr-dev/asr:main
  stage: test
  script:
    - pwd
    - cd asr/test
    - pytest --color=yes --numprocesses=auto --cov=asr --cov-report=html
    - coverage report

  coverage: '/TOTAL.+ ([0-9]+\.[0-9]+%)/'
  artifacts:
    paths:
      - coverage-html
    expire_in: 1 week


pages:
  stage: deploy
  dependencies:
    - main
  script:
    - mv coverage-html public
  artifacts:
    paths:
      - public
    expire_in: 3 weeks
  only:
    - master
