tests:
  image:  python:3.6
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev liblapack-dev libxc-dev
    - pip install flake8 coverage
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - flake8 asr
    - pip install git+https://gitlab.com/gpaw/gpaw.git
    - gpaw install-data paw-datasets --register
    - pytest --pyargs asr --cov=asr

docs_test:
  image: python:3.6
  script:
    - pip install .[docs]
    - which sphinx-build
    - cd $CI_PROJECT_DIR/docs
    - make html