image: python

stages:
- test
- integrationtest
- functionaltest
- build
- release

before_script:
- pip install pip --upgrade
- pip install -r dev-requirements.txt

# -------------- Style tests --------------
flake8:
  image: python:3.7
  stage: test
  script: tox -e flake8

readme:
  image: python:3.7
  stage: test
  script: tox -e readme

docs:
  stage: test
  script: tox -e docs

# -------------- Unit tests --------------
python36:
  image: python:3.6
  stage: test
  script: tox -e py36 -- -k ci

python37:
  image: python:3.7
  stage: test
  script: tox -e py37 -- -k ci

python38:
  image: python:3.8
  stage: test
  script: tox -e py38 -- -k ci

# -------------- Integration tests --------------
python36-gpaw:
  image: python:3.6
  stage: integrationtest
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev liblapack-dev libxc-dev
    - tox -e py36-gpaw -- -k integration_test_gpaw

python37-gpaw:
  image: python:3.7
  stage: integrationtest
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev liblapack-dev libxc-dev
    - tox -e py76-gpaw -- -k integration_test_gpaw

python38-gpaw:
  image: python:3.8
  stage: integrationtest
  script:
    - apt-get update -qy
    - apt-get install -qy libopenblas-dev liblapack-dev libxc-dev
    - tox -e py38-gpaw -- -k integration_test_gpaw

# -------------- Functional tests --------------

python36-gpaw-mpi:
  image: python:3.6
  stage: functionaltest
  script: tox -e py36-gpaw-mpi -- -k functional_test_gpaw
  tags:
    - long
    - gpaw

# -------------- Build --------------
build:
  stage: build
  script: tox -e build
  artifacts:
    paths:
    - dist/
    expire_in: 1 week

# -------------- Release --------------
# (Only on git tagged commit)
release:
  stage: release
  script: tox -e build
  artifacts:
    paths:
    - dist
  only:
  - tags