tests:
  image:  python:3.6
  script:
    - pip install flake8 spglib
    - pip install -e .
    - pip install git+https://gitlab.com/ase/ase.git
    - flake8 asr
    - python3 -m pytest asr/tests/test_cli.py --tb=short
    - python3 -m asr.tests.emt
