# Taken from gitlab flake8 repo
[tox]
minversion=2.3.1
envlist = clean,py36,py37,py38,flake8,linters,docs,{py36,py37,py38}-gpaw

[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase


[testenv]
setenv =
    HOME = {envdir}
deps =
    pytest
    pytest-cov
    hypothesis
    pyfakefs
commands =
    gpaw: {[testenv:gpaw]commands}
    pytest --basetemp={envtmpdir} --cov=asr --cov-append --cov-report=term-missing {posargs}

[testenv:gpaw]
commands =
    pip install gpaw
    gpaw -T install-data paw-datasets --register

# Autoformatter
[testenv:black]
basepython = python3
skip_install = true
deps =
    black>=19.3b0
commands =
    black --line-length 78 asr/

# Linters
[testenv:flake8]
basepython = python3
skip_install = true
deps =
    flake8
    flake8-bugbear
    flake8-colors
    flake8-docstrings>=1.3.1
;    flake8-import-order>=0.9
;    flake8-typing-imports>=1.1
commands =
    flake8 asr/

[testenv:pylint]
basepython = python3
skip_install = true
deps =
    pyflakes
    pylint
commands =
    pylint asr/

[testenv:doc8]
basepython = python3
skip_install = true
deps =
    sphinx
    doc8
commands =
    doc8 docs/source/

[testenv:bandit]
basepython = python3
skip_install = true
deps =
    bandit
commands =
    bandit -r asr/

# Documentation
[testenv:docs]
basepython = python3
whitelist_externals=/usr/bin/make
deps =
    -rdocs/requirements.txt
commands =
    sphinx-build -E -W -c docs -b html docs docs/_build

[testenv:serve-docs]
basepython = python3
skip_install = true
changedir = docs/_build/html
deps =
commands =
    python -m http.server {posargs}

[testenv:readme]
basepython = python3
deps =
    readme_renderer
commands =
    python setup.py check -r -s

# Release tooling
[testenv:build]
basepython = python3
skip_install = true
deps =
    wheel
    setuptools
commands =
    python setup.py -q sdist bdist_wheel

[testenv:release]
basepython = python3
skip_install = true
deps =
    {[testenv:build]deps}
    twine >= 1.5.0
commands =
    {[testenv:build]commands}
    twine upload --skip-existing dist/*

# Flake8 Configuration
[flake8]
# Ignore some flake8-docstrings errors
# NOTE(sigmavirus24): While we're still using flake8 2.x, this ignore line
# defaults to selecting all other errors so we do not need select=E,F,W,I,D
# Once Flake8 3.0 is released and in a good state, we can use both and it will
# work well \o/
# ignore = D203, W503, E203
# exclude =
#     .tox,
#     .git,
#     __pycache__,
#     docs/source/conf.py,
#     build,
#     dist,
#     tests/fixtures/*,
#     *.pyc,
#     *.egg-info,
#     .cache,
#     .eggs
# max-complexity = 10
# import-order-style = google
# application-import-names = flake8
format = ${cyan}%(path)s${reset}:${yellow_bold}%(row)d${reset}:${green_bold}%(col)d${reset}: ${red_bold}%(code)s${reset} %(text)s